language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/device_info/device_info.ino
    - PLATFORMIO_CI_SRC=examples/pattern_simple/pattern_simple.ino
    - PLATFORMIO_CI_SRC=examples/pattern_roi/pattern_roi.ino
    - PLATFORMIO_CI_SRC=examples/image_upload/image_upload.ino

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=pro8MHzatmega328 --board=mkr1000USB
