language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/device_info
    - PLATFORMIO_CI_SRC=examples/pattern_simple
    - PLATFORMIO_CI_SRC=examples/pattern_roi
    - PLATFORMIO_CI_SRC=examples/image_upload

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=pro8MHzatmega328 --board=mkr1000USB
